version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3036"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tequila_db
      MYSQL_USER: tequilauser
      MYSQL_PASSWORD: tequila
    volumes:
      - /home/bruno/projetos/tequila_financa/data:/var/lib/mysql
