-- MySQL Script generated by MySQL Workbench
-- seg 04 mai 2020 20:33:31 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema public
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema public
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `public` DEFAULT CHARACTER SET utf8 ;
USE `public` ;

-- -----------------------------------------------------
-- Table `public`.`Endereco`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `public`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `public`.`Endereco` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `public`.`Usuario`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `public`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `public`.`Usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `endereco_id` BIGINT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `avatar` VARCHAR(255) NULL,
  `cpf_cnpj` VARCHAR(45) NULL,
  `renda` DECIMAL(15,2) NOT NULL,
  `tipo_renda` VARCHAR(255) NULL,
  `criado_em` DATETIME NOT NULL DEFAULT NOW(),
  `alterado_em` DATETIME NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Endereco`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `public`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `public`.`Usuario` (`email` ASC);

CREATE INDEX `fk_Endereco_idx` ON `public`.`Usuario` (`endereco_id` ASC);


-- -----------------------------------------------------
-- Table `public`.`Status`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `public`.`Status` ;

CREATE TABLE IF NOT EXISTS `public`.`Status` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `public`.`Carteira`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `public`.`Carteira` ;

CREATE TABLE IF NOT EXISTS `public`.`Carteira` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  `renda` DECIMAL(15,2) NOT NULL,
  `despesa` DECIMAL(15,2) NULL,
  `renda_extra` DECIMAL(15,2) NULL,
  `criado_em` DATETIME NOT NULL DEFAULT NOW(),
  `alterado_em` DATETIME NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `usuario_id`),
  CONSTRAINT `fk_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `public`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_status_id`
    FOREIGN KEY (`status`)
    REFERENCES `public`.`Status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_id_idx` ON `public`.`Carteira` (`usuario_id` ASC);

CREATE INDEX `fk_status_id_idx` ON `public`.`Carteira` (`status` ASC);


-- -----------------------------------------------------
-- Table `public`.`RendaAdicional`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `public`.`RendaAdicional` ;

CREATE TABLE IF NOT EXISTS `public`.`RendaAdicional` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `carteira_id` BIGINT NOT NULL,
  `valor` DECIMAL(15,2) NULL,
  `descricao` VARCHAR(255) NULL,
  `criado_em` DATETIME NOT NULL DEFAULT NOW(),
  `alterado_em` DATETIME NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_idx`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `public`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carteira_idx`
    FOREIGN KEY (`carteira_id`)
    REFERENCES `public`.`Carteira` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_idx_idx` ON `public`.`RendaAdicional` (`usuario_id` ASC);

CREATE INDEX `fk_carteira_idx_idx` ON `public`.`RendaAdicional` (`carteira_id` ASC);


-- -----------------------------------------------------
-- Table `public`.`DespesasFixas`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `public`.`DespesasFixas` ;

CREATE TABLE IF NOT EXISTS `public`.`DespesasFixas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor_previsto` DECIMAL(15,2) NULL,
  `parcela_de` INT NULL,
  `total_parcelas` INT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT NOW(),
  `alterado_em` DATETIME NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_idx`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `public`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_idx_idx` ON `public`.`DespesasFixas` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `public`.`DespesaVariavel`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `public`.`DespesaVariavel` ;

CREATE TABLE IF NOT EXISTS `public`.`DespesaVariavel` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `carteira_id` BIGINT NOT NULL,
  `valor` DECIMAL(15,2) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT NOW(),
  `alterado_em` DATETIME NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_idx`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `public`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carteira_id`
    FOREIGN KEY (`carteira_id`)
    REFERENCES `public`.`Carteira` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_idx_idx` ON `public`.`DespesaVariavel` (`usuario_id` ASC);

CREATE INDEX `fk_carteira_id_idx` ON `public`.`DespesaVariavel` (`carteira_id` ASC);


-- -----------------------------------------------------
-- Table `public`.`DespesaFixa`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `public`.`DespesaFixa` ;

CREATE TABLE IF NOT EXISTS `public`.`DespesaFixa` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `carteira_id` BIGINT NOT NULL,
  `listafixadespesas_id` BIGINT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor_previsto` DECIMAL(15,2) NULL,
  `valor` DECIMAL(15,2) NULL,
  `total_parcelas` INT NULL,
  `parcela_de` INT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT NOW(),
  `alterado_em` DATETIME NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `listafixadespesas_id`),
  CONSTRAINT `fk_usuario_idx`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `public`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carteira_id`
    FOREIGN KEY (`carteira_id`)
    REFERENCES `public`.`Carteira` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_listafixadespesa_idx`
    FOREIGN KEY (`listafixadespesas_id`)
    REFERENCES `public`.`DespesasFixas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_idx_idx` ON `public`.`DespesaFixa` (`usuario_id` ASC);

CREATE INDEX `fk_carteira_id_idx` ON `public`.`DespesaFixa` (`carteira_id` ASC);

CREATE INDEX `fk_listafixadespesa_idx_idx` ON `public`.`DespesaFixa` (`listafixadespesas_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `public`.`Endereco`
-- -----------------------------------------------------
START TRANSACTION;
USE `public`;
INSERT INTO `public`.`Endereco` (`id`, `rua`, `cep`, `numero`, `complemento`) VALUES (1, 'Rua André Gallo', '86540000', '101', 'ap 104 bl 4');

COMMIT;


-- -----------------------------------------------------
-- Data for table `public`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `public`;
INSERT INTO `public`.`Usuario` (`id`, `endereco_id`, `email`, `senha`, `nome`, `avatar`, `cpf_cnpj`, `renda`, `tipo_renda`, `criado_em`, `alterado_em`, `ativo`) VALUES (1, 1, 'brunoliveirabatista@gmail.com', '123456', 'Bruno Batista', '', '', 1650.00, '', '', '', );

COMMIT;


-- -----------------------------------------------------
-- Data for table `public`.`Status`
-- -----------------------------------------------------
START TRANSACTION;
USE `public`;
INSERT INTO `public`.`Status` (`id`, `nome`) VALUES (1, 'ABERTO');
INSERT INTO `public`.`Status` (`id`, `nome`) VALUES (2, 'FINALIZADO');
INSERT INTO `public`.`Status` (`id`, `nome`) VALUES (0, 'CANCELADO');

COMMIT;

