-- MySQL Script generated by MySQL Workbench
-- seg 04 mai 2020 19:51:11 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `endereco_id` BIGINT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `avatar` VARCHAR(255) NULL,
  `cpf_cnpj` VARCHAR(45) NULL,
  `renda` DECIMAL(15,2) NOT NULL,
  `tipo_renda` VARCHAR(255) NULL,
  `criado_em` DATETIME NOT NULL DEFAULT NOW(),
  `alterado_em` DATETIME NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `endereco_id`),
  CONSTRAINT `fk_Endereco`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `mydb`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `mydb`.`Usuario` (`email` ASC);

CREATE INDEX `fk_Endereco_idx` ON `mydb`.`Usuario` (`endereco_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Status` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carteira`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Carteira` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Carteira` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `status` INT NOT NULL DEFAULT 1,
  `renda` DECIMAL(15,2) NOT NULL,
  `despesa` DECIMAL(15,2) NULL,
  `renda_extra` DECIMAL(15,2) NULL,
  `criado_em` DATETIME NOT NULL DEFAULT NOW(),
  `alterado_em` DATETIME NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `usuario_id`, `status`),
  CONSTRAINT `fk_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_status_id`
    FOREIGN KEY (`status`)
    REFERENCES `mydb`.`Status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_id_idx` ON `mydb`.`Carteira` (`usuario_id` ASC);

CREATE INDEX `fk_status_id_idx` ON `mydb`.`Carteira` (`status` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`RendaAdicional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RendaAdicional` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RendaAdicional` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `carteira_id` BIGINT NOT NULL,
  `valor` DECIMAL(15,2) NULL,
  `descricao` VARCHAR(255) NULL,
  `criado_em` DATETIME NOT NULL DEFAULT NOW(),
  `alterado_em` DATETIME NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `carteira_id`, `usuario_id`),
  CONSTRAINT `fk_usuario_idx`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carteira_idx`
    FOREIGN KEY (`carteira_id`)
    REFERENCES `mydb`.`Carteira` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_idx_idx` ON `mydb`.`RendaAdicional` (`usuario_id` ASC);

CREATE INDEX `fk_carteira_idx_idx` ON `mydb`.`RendaAdicional` (`carteira_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`ListaFixaDespesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ListaFixaDespesas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ListaFixaDespesas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor_previsto` DECIMAL(15,2) NULL,
  `parcela_de` INT NULL,
  `total_parcelas` INT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT NOW(),
  `alterado_em` DATETIME NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `usuario_id`),
  CONSTRAINT `fk_usuario_idx`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_idx_idx` ON `mydb`.`ListaFixaDespesas` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`DespesasVariaveis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DespesasVariaveis` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DespesasVariaveis` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `carteira_id` BIGINT NOT NULL,
  `valor` DECIMAL(15,2) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT NOW(),
  `alterado_em` DATETIME NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `usuario_id`, `carteira_id`),
  CONSTRAINT `fk_usuario_idx`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carteira_id`
    FOREIGN KEY (`carteira_id`)
    REFERENCES `mydb`.`Carteira` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_idx_idx` ON `mydb`.`DespesasVariaveis` (`usuario_id` ASC);

CREATE INDEX `fk_carteira_id_idx` ON `mydb`.`DespesasVariaveis` (`carteira_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`DespesasFixas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DespesasFixas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DespesasFixas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `carteira_id` BIGINT NOT NULL,
  `listafixadespesas_id` BIGINT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor_previsto` DECIMAL(15,2) NULL,
  `valor` DECIMAL(15,2) NULL,
  `total_parcelas` INT NULL,
  `parcela_de` INT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT NOW(),
  `alterado_em` DATETIME NULL,
  `ativo` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `usuario_id`, `carteira_id`),
  CONSTRAINT `fk_usuario_idx`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carteira_id`
    FOREIGN KEY (`carteira_id`)
    REFERENCES `mydb`.`Carteira` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_listafixadespesa_idx`
    FOREIGN KEY ()
    REFERENCES `mydb`.`ListaFixaDespesas` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_idx_idx` ON `mydb`.`DespesasFixas` (`usuario_id` ASC);

CREATE INDEX `fk_carteira_id_idx` ON `mydb`.`DespesasFixas` (`carteira_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Endereco`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Endereco` (`id`, `rua`, `cep`, `numero`, `complemento`) VALUES (1, 'Rua André Gallo', '86540000', '101', 'ap 104 bl 4');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Usuario` (`id`, `endereco_id`, `email`, `senha`, `nome`, `avatar`, `cpf_cnpj`, `renda`, `tipo_renda`, `criado_em`, `alterado_em`, `ativo`) VALUES (1, 1, 'brunoliveirabatista@gmail.com', '123456', 'Bruno Batista', '', '', 1650.00, '', '', '', );

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Status`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Status` (`id`, `nome`) VALUES (1, 'ABERTO');
INSERT INTO `mydb`.`Status` (`id`, `nome`) VALUES (2, 'FINALIZADO');
INSERT INTO `mydb`.`Status` (`id`, `nome`) VALUES (0, 'CANCELADO');

COMMIT;

